app.py
from flask import Flask, url_for, request, redirect
from blueprints.authentication import authentication
from blueprints.stocks import stocks
from blueprints.categories import categories
import helpers

app = Flask(__name__)
app.register_blueprint(authentication)
app.register_blueprint(stocks)
app.register_blueprint(categories)


@app.route("/")
def main():
    auth_token = request.cookies.get("auth")
    if not auth_token:
        return redirect(url_for("authentication.login"))
    user = helpers.verify_token(auth_token)
    if not user:
        return redirect(url_for("authentication.login"))
    return redirect(url_for("stocks.stocks_page"))


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=80)

blueprints/authentication.py
from flask import Blueprint, request, render_template, make_response, url_for, redirect, flash
import helpers

authentication = Blueprint('authentication', __name__, template_folder='../templates')


@authentication.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        helpers.authenticate_user(request.form["mail"], request.form["passwd"])
        resp = make_response(redirect(url_for("stocks.stocks_page")))
        resp.set_cookie("auth", helpers.create_token({"sub": request.form["mail"]}),
                        helpers.ACCESS_TOKEN_EXPIRE_SECONDS)
        return resp
    return render_template("login.jinja2")


@authentication.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        user = {
            "mail": request.form["mail"],
            "password": request.form["passwd"],
            "currency": request.form["currency"]
        }
        """if request.form["orgid"]:
            user["orgid"]=request.form["orgid"]"""
        helpers.register(user)
    return render_template("register.jinja2")

blueprints/categories.py
from flask import Blueprint, request, render_template, make_response, url_for, redirect, flash
import helpers

categories = Blueprint('categories', __name__, template_folder='../templates')


@categories.route("/categories", methods=["GET", "POST"])
def categories_page():
    auth_token = request.cookies.get("auth")
    if not auth_token:
        return redirect(url_for("authentication.login"))
    user = helpers.verify_token(auth_token)
    if not user:
        return redirect(url_for("authentication.login"))
    if request.method == "POST":
        ni = {
            "user": user["_id"],
            "name": request.form['name'][0:50],
        }
        for i in helpers.database["categories"].find(ni):
            if i:
                cats = [name["name"] for name in helpers.database["categories"].find({"user": user["_id"]}).sort("name")]
                return render_template("categories.jinja2", categories=cats)
        helpers.database["categories"].insert_one(ni)
    cats = [name["name"] for name in helpers.database["categories"].find({"user": user["_id"]}).sort("name")]
    return render_template("categories.jinja2", categories=cats)

blueprints/stocks.py
from flask import Blueprint, request, render_template, make_response, url_for, redirect, flash, jsonify
import helpers
from datetime import datetime

stocks = Blueprint('stocks', __name__, template_folder='../templates')


@stocks.route("/stocks", methods=["GET", "POST"])
def stocks_page():
    auth_token = request.cookies.get("auth")
    if not auth_token:
        return redirect(url_for("authentication.login"))
    user = helpers.verify_token(auth_token)
    if not user:
        return redirect(url_for("authentication.login"))
    if request.method == "POST":
        date = request.form["date"].split("-")
        date = datetime(int(date[0]), int(date[1]), int(date[2]))
        itemquery = {
            "user": user["_id"],
            "nameid": request.form["name"][0:50].lower(),
            "category": request.form['category'],
        }
        item = helpers.database["stocks"].find_one(itemquery)
        if item:
            helpers.database["stocklogs"].insert_one({
                "item": item["_id"],
                "price": int(request.form['avg_value']),
                "amount": int(request.form['stock']),
                "date": date
            })
            helpers.database["stocks"].find_one_and_replace({"_id": item["_id"]},
                                                            helpers.calc_weighted_avg(item, request.form))
        else:
            ni = {
                "user": user["_id"],
                "nameid": request.form["name"][0:50].lower(),
                "category": request.form['category'],
                "displayname": request.form['name'][0:50],
                "unit": request.form['unit'],
                "average_price": int(request.form['avg_value']),
                "stock_size": int(request.form['stock'])
            }
            helpers.database["stocklogs"].insert_one({
                "item": helpers.database["stocks"].insert_one(ni).inserted_id,
                "price": int(request.form['avg_value']),
                "amount": int(request.form['stock']),
                "date": date
            })
    return render_template("stocks.jinja2", **helpers.process_stocks(user))


@stocks.route("/stocks/detail/<nameid>")
def get_detail(nameid):
    print(nameid)
    items = []
    if nameid == "":
        return jsonify("wrong format")
    stock_logs = helpers.database["stocks"].aggregate([
        {
            '$group': {
                '_id': '$_id',
                'nameid': {
                    '$first': '$nameid'
                }
            }
        }, {
            '$lookup': {
                'from': 'stocklogs',
                'localField': '_id',
                'foreignField': 'item',
                'as': 'logs'
            }
        }
    ])
    for item in stock_logs:
        if item["nameid"] == nameid:
            stock_logs = item
            break
    else:
        return jsonify("item not found")
    for item in stock_logs["logs"]:
        items.append({
            "date": item["date"],
            "price": item["price"],
            "amount": item["amount"]
        })
    return jsonify(items)

templates/app_base.jinja2
<html lang="uk">
<head>
    <title>SalesSnake - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://meyerweb.com/eric/tools/css/reset/reset.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
</head>
<body>
    <nav class="navbar">
        <ul class="navlist center">
            <li class="navitem"><a class="navbutton" href="{{ url_for('stocks.stocks_page') }}">Stocks</a></li>
            <li class="navitem"><a class="navbutton" href="{{ url_for('categories.categories_page') }}">Categories</a></li>
        </ul>
    </nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/base.jinja2
<html lang="uk">
<head>
    <title>SalesSnake - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://meyerweb.com/eric/tools/css/reset/reset.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
</head>
<body> 
    <nav class="navbar">
        <ul class="navlist center">
            <li class="navitem"><a class="navbutton" href="{{ url_for('authentication.register') }}">Register</a></li>
            <li class="navitem"><a class="navbutton" href="{{ url_for('authentication.login') }}">Log in</a></li>
        </ul>
    </nav>
    <div class="content center">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/categories.jinja2
{% extends 'app_base.jinja2' %}
{% block title %}Stocks{% endblock %}
{% block content %}
    <div class="navbar">
        <ul class="navlist">
            <li class="navitem"><a class="navbutton" onclick="openForm()">Add Category</a></li>
        </ul>
    </div>
    <h2 class="title">Categories</h2>
    <div id="addStock" class="center">
        <div class="form center">
            <form method="post">
                <label for="name">Name</label>
                <input class="ffield" type="text" id="name" name="name" maxlength="50">
                <div class="fbuttons">
                    <input class="fbutton" type="reset" onclick="closeForm()" placeholder="Close">
                    <input class="fbutton" type="submit" placeholder="Add">
                </div>
            </form>
        </div>
    </div>
    <div class="table center">
        <table class="items">
        <tr class="item header">
            <td>Name</td>
        </tr>
        {% for name in categories %}
            <tr class="item">
                <td>{{ name }}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}

templates/login.jinja2
{% extends 'base.jinja2' %}
{% block title %}Log in{% endblock %}
{% block content %}
    <h1 class="center ftext">Please Log into your SalesSnake account.</h1>
    <div class="center form">
    <form method="post">
        <input name="mail" class="ffield" type="text" placeholder="e-mail">
        <input name="passwd" class="ffield" type="password" placeholder="Password">
        <input class="button" type="submit" value="Log In">
    </form>
    </div>
{% endblock %}

templates/register.jinja2
{% extends 'base.jinja2' %}
{% block title %}Log in{% endblock %}
{% block content %}
    <h1 class="center ftext">Please fill the form below to register.</h1>
    <div class="center form">
    <form method="post">
        <input name="mail" class="ffield" type="text" placeholder="e-mail">
        <input name="currency" class="ffield" type="text" placeholder="Currency">
        <input name="passwd" class="ffield" type="password" placeholder="Password" onchange="">
        <input name="passwd2" class="ffield" type="password" placeholder="Verify Password" onchange="">
        <input class="button" type="submit" value="Register">
    </form>
    </div>
{% endblock %}

templates/stocks.jinja2
{% extends 'app_base.jinja2' %}
{% block title %}Stocks{% endblock %}
{% block content %}
    <div class="navbar">
        <ul class="navlist">
            <li class="navitem"><a class="navbutton" onclick="toggle_add_form()">Add Stock</a></li>
        </ul>
    </div>
    <h2 class="title">Stocks</h2>
    <div id="addStock" class="modalWindow" style="display: none">
        <div class="form center">
            <form method="post">
                <label for="category">Product Category</label>
                <select class="ffield" id="category" name="category">
                    {% for category in cats %}
                        <option>{{ category }}</option>
                    {% endfor %}
                </select>
                <label for="name">Stock Name</label>
                <input class="ffield" type="text" id="name" name="name" maxlength="50">
                <label for="unit">Unit</label>
                <select class="ffield" id="unit" name="unit">
                    {% for unit in units %}
                        <option>{{ unit }}</option>
                    {% endfor %}
                </select>
                <label for="stock">Stock Quantity</label>
                <input class="ffield" type="number" id="stock" name="stock">
                <label for="avg_value">Purchase Price per Unit</label>
                <input class="ffield" type="number" id="avg_value" name="avg_value">
                <label for="date">Date</label>
                <input class="ffield" type="date" id="date" name="date" value="{{ today }}" max="{{ today }}">
                <div class="fbuttons">
                    <button type="reset" class="fbutton" onclick="toggle_add_form()">Close</button>
                    <button class="fbutton">Add</button>
                </div>
            </form>
        </div>
    </div>
    <div class="table center">
        <table class="items">
            <tr class="item header">
                <td>Category</td>
                <td>Stock Name</td>
                <td>Unit</td>
                <td>Stock Quantity</td>
                <td>Average value</td>
                <td>Total value</td>
                <td>Detail</td>
            </tr>
            {% for item in stocks %}
                <tr class="item">
                    <td>{{ item.category }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.unit }}</td>
                    <td>{{ item.stock_amount }} {{ item.unit }}</td>
                    <td class="money">{{ item.avg_value }}{{ currency }}</td>
                    <td class="money">{{ item.total_value }}{{ currency }}</td>
                    <td><button class="btnedit" onclick="toggle_detail('{{ item.nameid }}')">Detail</button></td>
                </tr>
            {% endfor %}
            <tr class="item">
                    <td colspan="5">Total price</td>
                    <td class="money" colspan="2">{{ total_price }}{{ currency }}</td>
            </tr>
        </table>
    </div>
<div id="detailform" style="display: none;" class="modalWindow">
    <div>
        <div class="buttons center">
            <button class="btndetail" onclick="toggle_detail()">X</button>
            <button class="btndetail" onclick="toggle_edit()">Edit</button>
            <button class="btndetail" onclick="toggle_sale()">Satış</button>
        </div>
        <div class="table center" id="itemhistory">

        </div>
    </div>
</div>

{% endblock %}